"""empty message

Revision ID: 0e7c7a232f76
Revises: 82a4ad93c22b
Create Date: 2024-03-21 10:50:06.072909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7c7a232f76'
down_revision = '82a4ad93c22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plaid_items_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_plaid_items_user_id_account_users'), 'account_users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_plaid_items_user_id_account_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_plaid_items_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
