"""empty message

Revision ID: b0d1e8e18ee4
Revises: 36aab94fa6f7
Create Date: 2024-03-22 18:11:08.911364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d1e8e18ee4'
down_revision = '36aab94fa6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_finance_category_primary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('personal_finance_category_detail', sa.Text(), nullable=True))
        batch_op.drop_column('merchant_name')
        batch_op.drop_column('personal_finance_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_finance_category', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('merchant_name', sa.TEXT(), nullable=True))
        batch_op.drop_column('personal_finance_category_detail')
        batch_op.drop_column('personal_finance_category_primary')

    # ### end Alembic commands ###
