"""empty message

Revision ID: c9bad2b7bbc7
Revises: 67aa7ebd50ab
Create Date: 2024-03-20 16:34:20.151967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bad2b7bbc7'
down_revision = '67aa7ebd50ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_account_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_account_id_accounts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_account_id_users', 'users', ['account_id'], ['id'])

    # ### end Alembic commands ###
