"""empty message

Revision ID: e28a8725db07
Revises: 8c2bb4097f7d
Create Date: 2024-03-25 21:06:12.831110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28a8725db07'
down_revision = '8c2bb4097f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.TEXT(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('cursor',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.alter_column('cursor',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sa.BLOB(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
